### ISSUE TITLE
Positioning and Misc

### ISSUE THREAD

**Issue by KhajitFFXI** [AliekberFFXI/xivcrossbar#7]
Bard songs have no accounting for pianissimo (regular or gearswaps that automatically use it)when selecting binds through gui. (stpt, stpc)

Cursna, erase, other -na spells, and haste 1/2 have stnpc in the gui instead of stpc.

Add new sets is prone to deleting everything if the wrong buttons are pressed. I think it's tied to pressing the Dpad down after selecting add new sets before hitting enter or without ending the process of adding a new set via hitting the start button or typing the new set name and confirming with enter. Basically a hidden delete all sets option if you press down while selecting "add new set."

The ability to move the crossbar in the gui would be nice or an explanation of what I should edit to not break everything if I try editing manually. It's perfectly situated to not let me have room for some plugins I use without screen clutter or jank empty chatlog windows to force an open space.

**Comment by AliekberFFXI** [comment]
I've updated songs to allow all self-targeting spells to also allow stpc and stpt targeting, and manually fixed the -na spells and Haste/II. The problem is in the resource files themselves, but I've patched it so it should work going forward.

To move the crossbar, just go into settings.xml and look for OffsetX and OffsetY. OffsetX will move the crossbar left/right, and OffsetY will move the crossbar up/down. I may add a UI way to move the crossbar at some point, but I'll have to give it some thought.

As for adding a new set deleting everything, I'm not able to reproduce that behavior. Can you see if you're able to do it with the newest version of XIVCrossbar? Some tangentially-related fixes might have already taken care of it.

**Comment by AliekberFFXI** [comment]
Added a menu option to reposition the crossbar. Since you haven't said anything about the crossbar set deletion in the FFXIAH thread, I'm going to close as fixed, but if you run into it again, please reopen this issue or file a new bug.
