### ISSUE TITLE
Private Server Question

### ISSUE THREAD

**Issue by benjaminrclayton** [AliekberFFXI/xivcrossbar#9]
Do you know if XIVCrossbar should work when connecting to private servers? I am trying to use the addon on Eden but the game hard crashes when attempting to load XIVCrossbar from the console.

Thanks!

**Comment by AliekberFFXI** [comment]
I can't think of any reason it wouldn't. Can you link a pastebin of your crash.log and console.log files from Windower? Right after crashing again, ideally.

**Comment by By-T0r** [comment]
It most likely the server parameter in the player:initialize function causing an error. In order to make this addon work on classic servers I've been having to passing an empty string for this parameter.

**Comment by AliekberFFXI** [comment]
Yeah, that could be it. Since you don't consume Windower's updates, you should be OK to manually edit the server resource file.

Run `input /echo windower.ffxi.get_info().server` in your Windower console (without the addon loaded), and write down the number that it outputs. Then open up Windower4/res/servers.lua and add a line to it with something like `[1] = {id=1,en="Eden"},` with that number it printed in place of the `1`s. It's a hack that wouldn't normally work because the resources get automatically updated, but since they don't get updated in your case, it should work.

**Comment by AliekberFFXI** [comment]
Just pushed a fix. If you already used a workaround to put your character files in an Eden folder, you can either rename the Eden folder to UnknownServer, or change line 159 in xivcrossbar from `server = 'UnknownServer'` to `server = 'Eden'`.

**Comment by seathasky** [comment]
Awesome! Will try this now!

**Comment by benjaminrclayton** [comment]
Still crashing for me as well. My theory is the out of date core windower files included in the eden installer are the culprit.

**Comment by seathasky** [comment]
https://user-images.githubusercontent.com/17598024/179052540-98da17c8-18ca-4207-a1a8-214d04bc4dda.mp4

This is what happens on Eden, i also changed "server = 'UnknownServer' to server = 'Eden' like you said.

**Comment by seathasky** [comment]
Is this getting looked at? No response from dev yet

**Comment by andre-macc** [comment]
The solution I've always used in private servers is to comment the following line (160):
`local server = resources.servers[windower.ffxi.get_info().server].en`
